
#ifndef VDECODER_CONFIG
#define VDECODER_CONFIG

#include "libcedarv.h"

#define BITSTREAM_FRAME_NUM         		(1024)
#define BITSTREAM_BUF_SIZE_IN_PREVIEW_MODE	(1024*1024)
#define BITSTREAM_FRAME_NUM_IN_PREVIEW_MODE (10)
#define MAX_SUPPORTED_VIDEO_WIDTH   		1920
#define MAX_SUPPORTED_VIDEO_HEIGHT  		1288

#define DECODE_FREE_RUN             1
#define DISPLAY_FREE_RUN            1

#endif

